### ISSUE TITLE
Missing rank of Whismur for Level Cap 50

### ISSUE THREAD

**Issue by Fabio1988** [Mygod/ohbem#12]
Hy I run into the following issue as I reworked PVP in RDM itself:

A hundo Whismur does not show as result in Level Cap 50 with ohbem calculation. Config:
```
leagues: {
  little: 500,
  great: 1500,
  ultra: 2500
},
levelCaps: [50, 51],
```

```
ohbem.queryPvPRank(
    /* pokemonId: */    293,
    /* form: */         1442,
    /* costume: */      0,
    /* gender: */       1,
    /* attack: */       15,
    /* defense: */      15,
    /* stamina: */      15,
    /* level: */        31,
  ));
```

The hundo at level 50 is exact at 1500 CP and is rank 1.

I remember that Ohbem filters all mons which does not reach the league CP with the level cap. But this Whismur does reach the league CP exactly?!

Result of ohbem:
```
{
  "great": [
    {"pokemon":294,"cap":51,"value":1797820,"level":50,"cp":1500,"percentage":0.99605,"rank":3}
  ],
  "ultra": [
    {"pokemon":295,"cap":50,"value":3939818,"level":45,"cp":2498,"percentage":0.97375,"rank":382}, 
    {"pokemon":295,"cap":51,"value":3939818,"level":45,"cp":2498,"percentage":0.96819,"rank":617}
  ]
}
```
Result of RDM:
```
{
  "great": [
    {"level":50,"cap":50,"gender":1,"rank":1,"cp":1500,"percentage":1,"form":0,"pokemon":294},
    {"form":0,"cp":1500,"cap":51,"pokemon":294,"gender":1,"rank":3,"percentage":0.9960541668374939,"level":50}
  ],
  "ultra": [
    {"cap":50,"cp":2498,"pokemon":295,"percentage":0.9737459602515445,"rank":382,"form":0,"gender":1,"level":45},
    {"cp":2498,"rank":617,"gender":1,"level":45,"percentage":0.9681931481705838,"form":0,"cap":51,"pokemon":295}
  ]
}
```

**Comment by Mygod** [comment]
Working as intended. Hundo is at 1500 CP and therefore not more than 1500 CP.

**Comment by Fabio1988** [comment]
So it's designed that the hundo must be more than 1500 CP? Why not more or equals?

But I'm fine with it, thx :)

**Comment by Mygod** [comment]
If the hundo is at most 1500 CP then rank 1 is trivially hundo so knowing the ranks aren't interesting since everything else is a strictly worse version of hundo. It does however calculate nontrivial ranks, like hundo Abra is rank 1 but at level 49/50.
