### ISSUE TITLE
Add Option to Eliminate Tied Rankings

### ISSUE THREAD

**Issue by plinytheelder** [Mygod/ohbem#15]
As mappers, we should always report the best Pokémon available. The only people who get excited about functional Rank 1's are users who don't have a map and thus have to settle. Should create an option to eliminate this feature/bug. Also eliminates confusion since the majority of users reference GO Stadium Rankings which do not use tied rankings.

**Comment by Mygod** [comment]
Replied here. https://github.com/Pupitar/ohbemgo/issues/9#issuecomment-1489088357
