### ISSUE TITLE
Return stats of pokemon by rank

### ISSUE THREAD

**Issue by jfberry** [Mygod/ohbem#8]
Currently ohbem will tell you the rank of a specific pokemon.  A reverse function would be useful - What if I want to know what stats I need for a top-ranked pokemon of a given type and form?

**Comment by Mygod** [comment]
No plan for this but will take PRs. Should be easy enough.

**Comment by jfberry** [comment]
See #9

**Comment by Mygod** [comment]
Fixed via #9.
